# Generated by Django 2.2.1 on 2019-06-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('cover_img_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SigInvitationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=45, unique=True)),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigs.Sig')),
            ],
        ),
        migrations.CreateModel(
            name='SigParticipate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_sig_leader', models.BooleanField(default=False)),
                ('sig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigs.Sig')),
            ],
            options={
                'unique_together': {('sig', 'user_id')},
            },
        ),
    ]
