# Generated by Django 2.2.1 on 2019-06-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sig',
            name='cover_img_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
